#!/bin/csh -f
set PDB  = '1UBQ.pdb 1MBO.pdb 1NWK.pdb'
set FACE = '0800 1200 1600 2000 2400'

foreach pdbfile ($PDB)

  set id = `echo $pdbfile:r:t`

  # convert PDB coordinates into XYZR
  ./pdb_to_xyzr ${id}.pdb | awk '{print $1,$2,$3,$4+1.1}' > ${id}.xyzr

  # generate triangular surfaces
  ./msms.i86Linux2.2.6.1 -density 1 -if ${id}.xyzr -of ${id} >& msms.log 

  #foreach edge ($EDGE)
  foreach face ($FACE)

    # convert MSMS output into GTS format
    msms2gts ${id} ${face}

    # run BE2, calculate tc
    be2 -gts ${id}.${face} >> ${id}.out

  end

end
